#!/usr/bin/python3
import sys
from math import *

def main():
    argv = sys.argv
    if len(sys.argv) == 1:
        sys.exit(84)
    if argv[1] == '-h' and len(sys.argv) == 2:
        help()
        sys.exit(0)
    if len(sys.argv) != 8:
        sys.exit(84)
    else:
        try :
            x0, y0, z0 = float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3])
            x1, y1, z1 = float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6])
            n = int(sys.argv[7])
        except ValueError:
            sys.exit(84)
        V1 = x1 - x0
        V2 = y1 - y0
        V3 = z1 - z0
        print ("The velocity vector of the ball is:")
        print ("(%.2f, %.2f, %.2f)" %(V1, V2, V3))
        x4 = x1 + V1 * n
        y4 = y1 + V2 * n
        z4 = z1 + V3 * n
        print("At time t + {0}, ball coordinates will be:".format(n))
        print ("(%.2f, %.2f, %.2f)" %(x4, y4, z4))

        produit_scalaire = sqrt(abs(pow(V1, 2) + pow(V2, 2) + pow(V3, 2)))
        if (produit_scalaire == 0):
            print ("The ball won't reach the paddle.")
            sys.exit(84)
        ang = 90 - (acos((abs(V3)) / produit_scalaire)) * 180 / pi
        if ((z1 - z0 == 0) & (z1 != 0)):
            print ("The ball won't reach the paddle.")
            sys.exit(0)
        if (-z1/(z1-z0) < 0):
            print ("The ball won't reach the paddle.")
            sys.exit(0)
        if (ang == 0 and y0 != 0):
            print ("The ball won't reach the paddle.")
            sys.exit(84)

        print ("The incidence angle is:")
        print ("%.2f degrees" % ang)
def help():
        print(" USAGE")
        print("    ./101pong x0 y0 z0 x1 y1 z1 n\n")
        print(" DESCRIPTION")
        print("     x0  ball abscissa at time t - 1")
        print("     y0  ball ordinate at time t - 1")
        print("     z0  ball altitude at time t - 1")
        print("     x1  ball abscissa at time t")
        print("     y1  ball ordinate at time t")
        print("     z1  ball altitude at time t")
        print("     n   time shift (greater than or equal to zero, integer)")
if __name__ == "__main__":
    main()